// localization for component

var locObj_Comp = {}; // localization object of component
locObj_Comp.en = {}; // english
locObj_Comp.de = {}; // german

locObj_Comp.en.richText_Title = 'Webuser administration';
locObj_Comp.de.richText_Title = 'Webanwender verwalten';
locObj_Comp.en.button_Transaction_New = 'New payment';
locObj_Comp.de.button_Transaction_New = 'Neue Zahlung';
locObj_Comp.en.richText_DLOG_Transcation_Title = 'New payment';
locObj_Comp.de.richText_DLOG_Transcation_Title = 'Neue Zahlung';
locObj_Comp.en.button_DLOG_Transaction_OK = 'Save';
locObj_Comp.de.button_DLOG_Transaction_OK = 'Sichern';
locObj_Comp.en.button_DLOG_Transaction_Cancel = 'Cancel';
locObj_Comp.de.button_DLOG_Transaction_Cancel = 'Abbrechen';
locObj_Comp.en.label1 = 'Amount EUR';
locObj_Comp.de.label1 = 'Betrag EUR';
locObj_Comp.en.label2 = 'Date received';
locObj_Comp.de.label2 = 'Buchungsdatum';
locObj_Comp.en.label3 = 'Account';
locObj_Comp.de.label3 = 'Konto';
locObj_Comp.en.label4 = 'Comment';
locObj_Comp.de.label4 = 'Bemerkung';

locObj_Comp.en.Grid_Webuser_Col_Header_Name = {};
locObj_Comp.de.Grid_Webuser_Col_Header_Name = {};
locObj_Comp.en.Grid_Webuser_Col_Header_Name.Selector = '#component_Main_dataGrid_Webuser .waf-widget-header .waf-dataGrid-col-Name .content';
locObj_Comp.de.Grid_Webuser_Col_Header_Name.Selector = '#component_Main_dataGrid_Webuser .waf-widget-header .waf-dataGrid-col-Name .content';
locObj_Comp.en.Grid_Webuser_Col_Header_Name.Value = 'Name';
locObj_Comp.de.Grid_Webuser_Col_Header_Name.Value = 'Name';
locObj_Comp.en.Grid_Webuser_Col_Header_Credits = {};
locObj_Comp.de.Grid_Webuser_Col_Header_Credits = {};
locObj_Comp.en.Grid_Webuser_Col_Header_Credits.Selector = '#component_Main_dataGrid_Webuser .waf-widget-header .waf-dataGrid-col-Creditpoint_Balance .content';
locObj_Comp.de.Grid_Webuser_Col_Header_Credits.Selector = '#component_Main_dataGrid_Webuser .waf-widget-header .waf-dataGrid-col-Creditpoint_Balance .content';
locObj_Comp.en.Grid_Webuser_Col_Header_Credits.Value = 'Credits';
locObj_Comp.de.Grid_Webuser_Col_Header_Credits.Value = 'Kredite';
locObj_Comp.en.Grid_Webuser_Col_Header_EUR = {};
locObj_Comp.de.Grid_Webuser_Col_Header_EUR = {};
locObj_Comp.en.Grid_Webuser_Col_Header_EUR.Selector = '#component_Main_dataGrid_Webuser .waf-widget-header .waf-dataGrid-col-EUR_Balance .content';
locObj_Comp.de.Grid_Webuser_Col_Header_EUR.Selector = '#component_Main_dataGrid_Webuser .waf-widget-header .waf-dataGrid-col-EUR_Balance .content';
locObj_Comp.en.Grid_Webuser_Col_Header_EUR.Value = 'EUR';
locObj_Comp.de.Grid_Webuser_Col_Header_EUR.Value = 'EUR';
locObj_Comp.en.Grid_Webuser_Col_Kind_Chat = 'Chat';
locObj_Comp.de.Grid_Webuser_Col_Kind_Chat = 'Chat';
locObj_Comp.en.Grid_Webuser_Col_Kind_Payment = 'Payment';
locObj_Comp.de.Grid_Webuser_Col_Kind_Payment = 'Zahlung';
locObj_Comp.en.Grid_Webuser_Col_Kind_Welcome_Credit = 'Welcome';
locObj_Comp.de.Grid_Webuser_Col_Kind_Welcome_Credit = 'Willkommen';

locObj_Comp.en.Grid_Transactions_Col_Date_Entered = {};
locObj_Comp.de.Grid_Transactions_Col_Date_Entered = {};
locObj_Comp.en.Grid_Transactions_Col_Date_Entered.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Date_Time_Entered .content';
locObj_Comp.de.Grid_Transactions_Col_Date_Entered.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Date_Time_Entered .content';
locObj_Comp.en.Grid_Transactions_Col_Date_Entered.Value = 'Date entered';
locObj_Comp.de.Grid_Transactions_Col_Date_Entered.Value = 'Eingabedatum';
locObj_Comp.en.Grid_Transactions_Col_Kind = {};
locObj_Comp.de.Grid_Transactions_Col_Kind = {};
locObj_Comp.en.Grid_Transactions_Col_Kind.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Kind .content';
locObj_Comp.de.Grid_Transactions_Col_Kind.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Kind .content';
locObj_Comp.en.Grid_Transactions_Col_Kind.Value = 'Kind';
locObj_Comp.de.Grid_Transactions_Col_Kind.Value = 'Art';
locObj_Comp.en.Grid_Transactions_Col_EUR = {};
locObj_Comp.de.Grid_Transactions_Col_EUR = {};
locObj_Comp.en.Grid_Transactions_Col_EUR.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-EUR .content';
locObj_Comp.de.Grid_Transactions_Col_EUR.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-EUR .content';
locObj_Comp.en.Grid_Transactions_Col_EUR.Value = 'EUR';
locObj_Comp.de.Grid_Transactions_Col_EUR.Value = 'EUR';
locObj_Comp.en.Grid_Transactions_Col_Credits = {};
locObj_Comp.de.Grid_Transactions_Col_Credits = {};
locObj_Comp.en.Grid_Transactions_Col_Credits.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Amount_of_Credits .content';
locObj_Comp.de.Grid_Transactions_Col_Credits.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Amount_of_Credits .content';
locObj_Comp.en.Grid_Transactions_Col_Credits.Value = 'Credits';
locObj_Comp.de.Grid_Transactions_Col_Credits.Value = 'Kredite';
locObj_Comp.en.Grid_Transactions_Col_Account = {};
locObj_Comp.de.Grid_Transactions_Col_Account = {};
locObj_Comp.en.Grid_Transactions_Col_Account.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Account .content';
locObj_Comp.de.Grid_Transactions_Col_Account.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Account .content';
locObj_Comp.en.Grid_Transactions_Col_Account.Value = 'Account';
locObj_Comp.de.Grid_Transactions_Col_Account.Value = 'Konto';
locObj_Comp.en.Grid_Transactions_Col_Date_Received = {};
locObj_Comp.de.Grid_Transactions_Col_Date_Received = {};
locObj_Comp.en.Grid_Transactions_Col_Date_Received.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Date_Time_Payment_Received .content';
locObj_Comp.de.Grid_Transactions_Col_Date_Received.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Date_Time_Payment_Received .content';
locObj_Comp.en.Grid_Transactions_Col_Date_Received.Value = 'Date received';
locObj_Comp.de.Grid_Transactions_Col_Date_Received.Value = 'Buchungsdatum';
locObj_Comp.en.Grid_Transactions_Col_Comment = {};
locObj_Comp.de.Grid_Transactions_Col_Comment = {};
locObj_Comp.en.Grid_Transactions_Col_Comment.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Comment .content';
locObj_Comp.de.Grid_Transactions_Col_Comment.Selector = '#component_Main_dataGrid_Webuser_Transactions .waf-widget-header .waf-dataGrid-col-Comment .content';
locObj_Comp.en.Grid_Transactions_Col_Comment.Value = 'Comment';
locObj_Comp.de.Grid_Transactions_Col_Comment.Value = 'Bermerkung';

var locStr_Admin_Webuser = {}; // localization strings Webuser Administration
locStr_Admin_Webuser.en = {}; // english
locStr_Admin_Webuser.de = {}; // german

locStr_Admin_Webuser.en.No_Webuser_selected = 'No Webuser selected.';
locStr_Admin_Webuser.de.No_Webuser_selected = 'Kein Webuser ausgewählt.';
locStr_Admin_Webuser.en.No_amount_entered = 'No amount entered.';
locStr_Admin_Webuser.de.No_amount_entered = 'Kein Betrag eingegeben.';
locStr_Admin_Webuser.en.Amount_out_of_range = 'The amount must be in the range ± 1 - 1000.';
locStr_Admin_Webuser.de.Amount_out_of_range = 'Der Betrag muß im Bereich ± 1 - 1000 sein.';
locStr_Admin_Webuser.en.No_receiving_date_entered = 'No recieving date entered.';
locStr_Admin_Webuser.de.No_receiving_date_entered = 'Kein Buchungsdatum eingegeben.';
locStr_Admin_Webuser.en.Invalid_date = 'Invalid date.';
locStr_Admin_Webuser.de.Invalid_date = 'Ungültiges Datum.';
locStr_Admin_Webuser.en.Receiving_Date_out_of_range = 'The receving date must not be more than 10 days in the past and 3 days in the future.';
locStr_Admin_Webuser.de.Receiving_Date_out_of_range = 'Das Buchungsdatum darf nicht mehr als 10 Tage in der Vergangenheit und 3 Tage in der Zukunft liegen.';
locStr_Admin_Webuser.en.No_account_entered = 'No account entered.';
locStr_Admin_Webuser.de.No_account_entered = 'Kein Konto angegeben.';
locStr_Admin_Webuser.en.richText_DLOG_Transcation_Title = 'New payment for %1';
locStr_Admin_Webuser.de.richText_DLOG_Transcation_Title = 'Neue Zahlung für %1';
locStr_Admin_Webuser.en.Invalid_Webuser = 'Invalid Webuser.';
locStr_Admin_Webuser.de.Invalid_Webuser = 'Ungültiger Webuser.';
